package com.codeWithhHemant.blog.controllers;

import com.codeWithhHemant.blog.paylods.JwtAuthResponse;
import com.codeWithhHemant.blog.security.JwtTokenHelper;
import com.codeWithhHemant.blog.paylods.UserLoginDetails;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("api")
public class UserLoginController {

    @Autowired
    AuthenticationManager authenticationManager;

    @Autowired
    JwtTokenHelper jwtTokenHelper;

    @PostMapping("login")
    public ResponseEntity<?> login(@Valid @RequestBody UserLoginDetails details){
        Authentication authentication = authenticationManager    //this authenticate mehtod may generate BadCredentials(That we have Handeled Globally) exception that is generated by DaoAuthenticationprovider when user Or password not match with given login details. And UserNotFoundException is throwen when when the provider calls loadUserByUserName and the user is not present in data base.
                           .authenticate(new UsernamePasswordAuthenticationToken(details.getUserName(),details.getPassword()));

        String token = null;

        if(authentication.isAuthenticated()){
             token = jwtTokenHelper.generateToken(details.getUserName());
        }

        return new ResponseEntity<>(new JwtAuthResponse(token),HttpStatus.OK);
    }
}
